### PR TITLE
Move migration screen to within the room list

### LINKED ISSUE #2310: Move migration screen to within the room list
The current migration screen blocks the user from accessing the rest of the app, especially bug reporting and logs. This is a problem when setting up custom backend stacks.
We have agreed with product to move it from a modal to a state of the room list similar to what has been done on iOS here https://github.com/element-hq/element-x-ios/pull/2389

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other : screen redesign.

## Content

- Moves the `migration` package contents from `:features:ftue` to `:features:messages:impl`.
- Adds light variant of the migration screen.
- Updates compound version to `v0.0.4` to fix status bar tinting issues.
- Displays the migration screen inside the room list one, allowing the user to send bug reports if needed, while preventing some other actions such as searching or creating a new room.

## Motivation and context

Closes #2310.

## Screenshots / GIFs

Inside the PR. There are also changes to the wait list screen since it reuses the same `SunsetPage` component, but I believe this is the desired behaviour.

Here's also a video with the current behaviour:

https://github.com/element-hq/element-x-android/assets/480955/29405a9f-66ca-46c0-86c8-3b7cf635a407

## Tests

- Remove all data from the EX app.
- Sign in again.
- Go through the FTUE screens quickly.
- With some luck, you'll still be able to see the migration screen and interact with the empty avatar icon now to open the settings.
- The migration screen should only appear once.

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 14

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

### CODE REVIEW

File: features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/state/DefaultFtueState.kt [hunk 1]
```diff
@@ -97,17 +87,16 @@ class DefaultFtueState @Inject constructor(
...
             { shouldDisplayLockscreenSetup() },
         ).any { it() }
     }
 
-    private fun shouldDisplayMigrationScreen(): Boolean {
-        return migrationScreenStore.isMigrationScreenNeeded(matrixClient.sessionId)
-    }
+//    private fun shouldDisplayMigrationScreen(): Boolean {
+//        return migrationScreenStore.isMigrationScreenNeeded(matrixClient.sessionId)
+//    }
```
Comment (bmarty) [inline features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/state/DefaultFtueState.kt:99]: Maybe just remove this.

File: features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/migration/MigrationScreenView.kt [hunk 2]
```diff
@@ -14,45 +14,43 @@
...
-    }
-    SunsetPage(
-        modifier = modifier,
-        isLoading = true,
-        title = stringResource(id = R.string.screen_migration_title),
-        subtitle = stringResource(id = R.string.screen_migration_message),
-        overallContent = {}
+    val displayMigrationStatusFadeProgress by animateFloatAsState(
+        targetValue = if (isMigrating) 1f else 0f,
+        animationSpec = tween(durationMillis = 1000),
```
Comment (bmarty) [inline features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/migration/MigrationScreenView.kt:38]: 1s is maybe a bit long, can we reduce the duration for a snappier effect!

File: tests/uitests/src/test/snapshots/images/ui_S_t[f.login.impl.screens.waitlistscreen_WaitListView_null_WaitListView-Day-8_9_null_0,NEXUS_5,1.0,en].png
Comment (bmarty) [inline tests/uitests/src/test/snapshots/images/ui_S_t[f.login.impl.screens.waitlistscreen_WaitListView_null_WaitListView-Day-8_9_null_0,NEXUS_5,1.0,en].png:1]: (I do not see any diff here)

File: tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl_RoomListView_null_RoomListView-Day-3_4_null_12,NEXUS_5,1.0,en].png
Comment (bmarty) [inline tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl_RoomListView_null_RoomListView-Day-3_4_null_12,NEXUS_5,1.0,en].png:1]: (a bit weird to see the title "All chats" here, but OK, I have to get used to it!)

File: features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/state/DefaultFtueState.kt [hunk 3]
```diff
@@ -43,17 +41,14 @@ class DefaultFtueState @Inject constructor(
...
     private val permissionStateProvider: PermissionStateProvider,
     private val lockScreenService: LockScreenService,
-    private val matrixClient: MatrixClient,
 ) : FtueState {
     override val shouldDisplayFlow = MutableStateFlow(isAnyStepIncomplete())
 
     override suspend fun reset() {
         welcomeScreenState.reset()
         analyticsService.reset()
-        migrationScreenStore.reset()
```
Comment (bmarty) [inline features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/state/DefaultFtueState.kt:56]: I would add `migrationScreenStore.reset()` in `DefaultClearCacheUseCase`.

**Review by bmarty — APPROVED** [review]
LGTM, nice work!
Moving code like this is not easy, but you did it well!
