### PR TITLE
Font size on 'All Chats' was changing mid animation

### LINKED ISSUE #1572: Font size wrong on All Chats header text
### Steps to reproduce

1. Start EX
2. Slowly move roomlist up
3. Observe how All Chats appears in the header

#### What did you expect?
Text to fade in

#### What happened instead?
Text appears briefly in large font size, jumps to small and then fades in

https://github.com/vector-im/element-x-android/assets/640121/58a0e027-d9c8-4020-9dd1-a14780b47eb3

### Your phone model

Pixel 5

### Operating system version

Android 14

### Application version and app store

latest nightly

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Wraps `MediumTopAppBar` in a `MaterialTheme` with the custom text styles needed for small / large title set to the right values.
- Removes the workaround relying on `collapsedFraction`.

## Motivation and context

Fixes #1572.

## Screenshots / GIFs

https://github.com/element-hq/element-x-android/assets/480955/c60edf6d-1919-4473-90f5-2513a2b93d24

## Tests

- In the room list, slowly scroll up/down so the title collapses and grows again.

If there are no font size changes, it's working fine.

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 11

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

### CODE REVIEW

File: features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/components/RoomListTopBar.kt [hunk 1]
```diff
@@ -149,130 +150,131 @@ private fun DefaultRoomListTopBar(
...
-            title = {
-                val fontStyle = if (scrollBehavior.state.collapsedFraction > 0.5)
-                    ElementTheme.typography.aliasScreenTitle
-                else
-                    ElementTheme.typography.fontHeadingLgBold.copy(
-                        // Due to a limitation of MediumTopAppBar, and to avoid the text to be truncated,
-                        // ensure that the font size will never be bigger than 28.dp.
-                        fontSize = 28.dp.applyScaleDown().toSp()
+        val smallTextStyle = ElementTheme.typography.aliasScreenTitle
+        val largeTextStyle = ElementTheme.typography.fontHeadingLgBold.copy(
```
Comment (bmarty) [inline features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/components/RoomListTopBar.kt:154]: Neat: Maybe rename the 2 val for something with more semantic, for instance:
```kotlin
        val collapsedTextStyle = ElementTheme.typography.aliasScreenTitle
        val expandedTextStyle = ElementTheme.typography.fontHeadingLgBold.copy(
```

**Review by bmarty — APPROVED** [review]
Thanks for the fix, tested OK with my phone which has a bigger font settings. You rock!

File: features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/components/RoomListTopBar.kt [hunk 2]
```diff
@@ -149,130 +150,131 @@ private fun DefaultRoomListTopBar(
...
+            // Due to a limitation of MediumTopAppBar, and to avoid the text to be truncated,
+            // ensure that the font size will never be bigger than 28.dp.
+            fontSize = 28.dp.applyScaleDown().toSp()
+        )
+        MaterialTheme(
+            colorScheme = ElementTheme.materialColors,
+            shapes = MaterialTheme.shapes,
+            typography = ElementTheme.materialTypography.copy(headlineSmall = largeTextStyle, titleLarge = smallTextStyle),
```
Comment (bmarty) [inline features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/components/RoomListTopBar.kt:162]: ...would fix the reading `small = large, large = small` which looks like a bug :-)

File: features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/components/RoomListTopBar.kt (hunk 1 above)
Comment (jmartinesp) [reply features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/components/RoomListTopBar.kt:154]: I was trying to follow the nomenclature used in `TwoRowsTopAppBar`, but I can see how this can be confusing without more context. I'll do the change, thanks!

**Review by bmarty — APPROVED** [review]
