### PR TITLE
Reactions power level

### LINKED ISSUE #2093: Long press menu offers reaction option despite no permissions
### Steps to reproduce

1. Go to a room where your power level will be too low to send reactions, e.g. https://matrix.to/#/#jellyfin-announce:matrix.org
2. Long press a message, or try clicking existing reactions

#### What did you expect?
Reaction bar hidden in long press menu; clicking existing reactions not showing a split second +1 to count.

#### What happened instead?

https://github.com/element-hq/element-x-android/assets/46846000/fcd9e213-e782-4af6-8fd8-28a8a616530c

### Your phone model

Google Pixel 3

### Operating system version

Android 13

### Application version and app store

deff2d8, GHA debug build

### Homeserver

Synapse 1.98.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Consider the user power level to enable or disable the ability to send reaction.

## Motivation and context

Closes #2093 

## Screenshots / GIFs

No change, hence I could add preview for the case of power level is too low.

## Tests

- Change the power level require to send a reaction and observe the effect

ReactPermission

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/MessagesPresenter.kt [hunk 1]
```diff
@@ -139,6 +139,7 @@ class MessagesPresenter @AssistedInject constructor(
         val syncUpdateFlow = room.syncUpdateFlow.collectAsState()
         val userHasPermissionToSendMessage by room.canSendMessageAsState(type = MessageEventType.ROOM_MESSAGE, updateKey = syncUpdateFlow.value)
         val userHasPermissionToRedact by room.canRedactAsState(updateKey = syncUpdateFlow.value)
+        val userHasPermissionToSendReaction by room.canSendMessageAsState(type = MessageEventType.REACTION_SENT, updateKey = syncUpdateFlow.value)
```
Comment (bmarty) [inline features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/MessagesPresenter.kt:142]: The value `MessageEventType.REACTION_SENT` is quite non-obvious, but it's coming from the SDK...

**Review by jmartinesp — APPROVED** [review]
LGTM, thanks!
