### PR TITLE
Ensure sessionPath is not reused for different homeserver. Fixes not loading media issue.

### LINKED ISSUE #3296: Media failing to load
### Steps to reproduce

Various reports from #element-x-android:matrix.org that media doesn't always load. See rageshake(s)

#### What did you expect?

See media

#### What happened instead?

Get stuck on a blurhash

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

0.4.15

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Ensure the folder `sessionPath` is not reused for different homeserver, else some cached data may be wrong.
Rotate the folder and delete the previous one. One side effect is described in #3296 because API to get authentication media may or may not be available and this capability is stored in cache.

## Motivation and context

Closes #3296

## Screenshots / GIFs

NA

## Tests

- No session
- Continue with matrix.org but do not enter credentials.
- Go back
- Change the homeserver with one which does not support authenticated media (for instance element.io)
- Login to this homeserver

Before: media cannot be loaded
After: media can be loaded.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/auth/RustMatrixAuthenticationService.kt [hunk 1]
```diff
@@ -117,8 +126,9 @@ class RustMatrixAuthenticationService @Inject constructor(
 
     override suspend fun setHomeserver(homeserver: String): Result<Unit> =
         withContext(coroutineDispatchers.io) {
+            val emptySessionPath = rotateSessionPath()
```
Comment (jmartinesp) [inline libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/auth/RustMatrixAuthenticationService.kt:129]: Maybe `newSessionPath`?

**Review by jmartinesp — APPROVED** [review]
LGTM, thanks!
