### PR TITLE
Fix element call crash when resuming from notification

### LINKED ISSUE #3905: crash pressing the "Call in progress notification"
### Steps to reproduce

1. Start a call
2. Tap "Call in progress notification", Tap to return to the call
3. Crash

### Outcome

No Crash

### Your phone model

op9p

### Operating system version

crdroid 9.7 on android 13

### Application version and app store

0.7.3 from gplay

### Homeserver

1.119.0+bookworm1

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Ensure that when the call is resume when clicking on the notification, the app does not crash.

Seems that this is a regression from #3833.

## Motivation and context

Fix #3905 

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/ElementCallActivity.kt [hunk 1]
```diff
@@ -92,6 +93,10 @@ class ElementCallActivity :
         )
 
         setCallType(intent)
+        // If presenter is not created at this point, it means we have no call to display, the Activity is finishing, so return early
+        if (!::presenter.isInitialized) {
+            return
+        }
```
Comment (bmarty) [inline features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/ElementCallActivity.kt:99]: Not strictly necessary, but should prevent future crash...

**Review by ganfra — APPROVED** [review]
