### PR TITLE
Fix crash about several DataStores using the same file

### LINKED ISSUE #2308: Lots of crashes with "There are multiple DataStores active for the same file"
### Steps to reproduce

Dunno, but lots of anecdata and rageshakes showing this crash:

`01-26 12:25:00.094 25836 25836 E AndroidRuntime: java.lang.IllegalStateException: There are multiple DataStores active for the same file: /data/user/0/io.element.android.x/files/datastore/session_@user:example.com_preferences.preferences_pb. You should either maintain your DataStore as a singleton or confirm that there is no two DataStore's active on the same file (by confirming that the scope is cancelled).`

#### What did you expect?

no crash

#### What happened instead?

crash

### Your phone model

Pixel 7a

### Operating system version

Android 14

### Application version and app store

Element X nightly/0.4.2-nightly (Google Pixel 7a; Android 14; UQ1A.240105.004.2024012600; Sdk TODO)

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Fix crash about several DataStores using the same file
	- Create `@SessionCoroutineScope` annotation to pass a session-managed coroutine scope to the DI.
	- Expose this scope from `MatrixClient`.
	- Rework SessionPreferencesStore file creation a bit. Use this coroutine scope to initialize the data store, so it's stopped when the scope is cancelled.
- Make sure the whole item in advanced settings screen triggers the toggle action, to be consistent with the rest of the app.

## Motivation and context

Fixes #2308 (I hope).

## Tests

To be honest, I'm not 100% sure how to trigger this issue. I tried logging out and in again, which was my theory for why this was happening, but sadly I couldn't reproduce the issue.

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 14

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

### CODE REVIEW

File: app/src/main/kotlin/io/element/android/x/di/SessionComponent.kt [hunk 1]
```diff
@@ -33,6 +35,10 @@ interface SessionComponent : NodeFactoriesBindings {
     interface Builder {
         @BindsInstance
         fun client(matrixClient: MatrixClient): Builder
+
+        @BindsInstance
```
Comment (ganfra) [inline app/src/main/kotlin/io/element/android/x/di/SessionComponent.kt:39]: Why using `@BindsInstance` here? I'd just use `@Provides`

**Review by ganfra — APPROVED** [review]
One remark otherwise LGTM

File: app/src/main/kotlin/io/element/android/x/di/SessionComponent.kt (hunk 1 above)
Comment (jmartinesp) [reply app/src/main/kotlin/io/element/android/x/di/SessionComponent.kt:39]: Won't `@Provides` need the function to be implemented?

Comment (ganfra) [reply app/src/main/kotlin/io/element/android/x/di/SessionComponent.kt:39]: We already have lots of @Provides in the `SessionMatrixModule`. I'd use the builder only for things we got from the outer world.

Comment (jmartinesp) [reply app/src/main/kotlin/io/element/android/x/di/SessionComponent.kt:39]: Oh, now I see what you mean. Yeah, a provides is better here.

**Comment by bmarty** [comment]
@jmartinesp  I can repro the crash systematically by:
- opening the app
- open a timeline
- clicking back twice to show the device home
- opening a room timeline from a notification.

But they are other recipes, for instance:
- open a room
- click back twice
- open the app again
- sometimes it crashes the app.

File: changelog.d/2308.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix 'There are multiple DataStores active for the same file' crashes
```
Comment (bmarty) [inline changelog.d/2308.bugfix:1]: I am tempted to say that it's not necessary to add a file for the changelog, since the crash was not on the previous release.

**Comment by jmartinesp** [comment]
@bmarty thanks for the reproducible steps! Sadly, it seems like the fix does not really fix the issue then... I'll keep trying.

File: libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+import io.element.android.libraries.di.SingleIn
+import io.element.android.libraries.di.annotations.SessionCoroutineScope
+import io.element.android.libraries.matrix.api.user.CurrentSessionIdHolder
+import kotlinx.coroutines.CoroutineScope
+
+@Module
+@ContributesTo(SessionScope::class)
+object SessionPreferencesModule {
+    @Provides
+    @SingleIn(SessionScope::class)
```
Comment (bmarty) [inline libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt:33]: I think `@SingleIn(SessionScope::class)` is not necessary here. `defaultSessionPreferencesStoreFactory` is already handling the concurrency access.

File: libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+    fun providesSessionPreferencesStore(
+        defaultSessionPreferencesStoreFactory: DefaultSessionPreferencesStoreFactory,
+        currentSessionIdHolder: CurrentSessionIdHolder,
```
Comment (bmarty) [inline libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt:36]: Since this object has the scope `SessionScope`, can we inject directly the `sessionId: String` instead of the `CurrentSessionIdHolder`?

Oh actually `CurrentSessionIdHolder` is not what I though. It's not really a `Holder`, but more an accessor (or a provider). I think it will be simpler to provide the `sessionId` in `SessionMatrixModule` like some other fields and remove `CurrentSessionIdHolder`. Out of scope of this PR though.

File: libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultSessionPreferencesStoreFactory.kt [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+import java.util.concurrent.ConcurrentHashMap
+import javax.inject.Inject
+
+@SingleIn(AppScope::class)
+class DefaultSessionPreferencesStoreFactory @Inject constructor(
+    @ApplicationContext private val context: Context,
+) {
+    private val cache = ConcurrentHashMap<SessionId, DefaultSessionPreferencesStore>()
+
+    fun get(sessionId: SessionId, sessionCoroutineScope: CoroutineScope) = cache.getOrPut(sessionId) {
```
Comment (bmarty) [inline libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultSessionPreferencesStoreFactory.kt:34]: There is a warning here:
`Declaration has type inferred from a platform call, which can lead to unchecked nullability issues. Specify type explicitly as nullable or non-nullable.`

File: libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultSessionPreferencesStoreFactory.kt [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+        DefaultSessionPreferencesStore(context, sessionId, sessionCoroutineScope)
+    }
+
+    fun remove(sessionId: SessionId) = cache.remove(sessionId)
```
Comment (bmarty) [inline libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultSessionPreferencesStoreFactory.kt:38]: Not used?

File: libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultSessionPreferencesStoreFactory.kt [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+
+    fun clear() = cache.clear()
```
Comment (bmarty) [inline libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultSessionPreferencesStoreFactory.kt:40]: Not used, but I do not see in which case we may want to have such method. So maybe just remove it?

**Review by bmarty — COMMENTED** [review]
Glad to see that the issue is fixed!
I have some more remarks before we can merge this PR.

File: libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt (hunk 3 above)
Comment (jmartinesp) [reply libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt:33]: True, I was just keeping it there in case we can solve the underlying issue and remove `DefaultSessionPreferencesStoreFactory`. But it doesn't do anything at the moment, so we can remove it.

File: libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt (hunk 4 above)
Comment (jmartinesp) [reply libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt:36]: > I think it will be simpler to provide the sessionId in SessionMatrixModule like some other fields and remove CurrentSessionIdHolder. Out of scope of this PR though.

The problem is Anvil/Dagger doesn't understand that a `SessionId` is since it's Java based, for the DI library it's just a `String` and it won't allow you to inject it anywhere. That's why we had to create the holder wrapper. But maybe its name can be misleading.

File: libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultSessionPreferencesStoreFactory.kt (hunk 6 above)
Comment (jmartinesp) [reply libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultSessionPreferencesStoreFactory.kt:38]: Yeah, I might just remove this and `clear` until I create a way to clear these values in another PR (#2303 ?).

File: libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt (hunk 4 above)
Comment (bmarty) [reply libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/SessionPreferencesModule.kt:34]: We had [annotations](https://github.com/element-hq/element-android/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/StringQualifiers.kt#L21) to be able to inject `String`s in the previous project and it was quite handy.

**Review by bmarty — APPROVED** [review]
Thanks for the update!
