### PR TITLE
Skip device verification screen when creating a new account using OIDC

### LINKED ISSUE #3279: Device verification success screen appears after a fresh new registration #3126
### Steps to reproduce

1. Select a HS with a MAS accepting registration (ask if you do not know one)
2. Create an account

<details>
<summary>The device verification success screen unexpectly appears</summary>

</details>

#### What did you expect?
Enteting within the app and seeing an empty room list.

#### What happened instead?
I had to hit to Continue instead

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by bmarty**
## Content

It can happen that the session is automatically verified and in this case the FTUE verification step has to be skipped.

This PR handle this.

Note that some shortcut had been taken to show the confirmation screen when the user enter a recovery key, so I had to add a parameter `showDeviceVerifiedScreen` to handle this case properly.

## Motivation and context

Closes #3279

## Tests

- Login using OIDC, creating a new account
- The device verification screen must be skipped. A loader can be displayed for a short moment.

Note that I have seen the "Confirm your identity" for a few millis, it seems that the SDK emit a `SessionVerifiedStatus.NotVerified` between the `SessionVerifiedStatus.Unknown` and `SessionVerifiedStatus.Verified`, but I need to check again befor reporting to the SDK.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/verifysession/impl/src/main/kotlin/io/element/android/features/verifysession/impl/VerifySelfSessionPresenter.kt [hunk 1]
```diff
@@ -66,18 +75,32 @@ class VerifySelfSessionPresenter @Inject constructor(
         val recoveryState by encryptionService.recoveryStateStateFlow.collectAsState()
         val stateAndDispatch = stateMachine.rememberStateAndDispatch()
         val skipVerification by sessionPreferencesStore.isSessionVerificationSkipped().collectAsState(initial = false)
-        val needsVerification by sessionVerificationService.needsSessionVerification.collectAsState(initial = true)
+        val sessionVerifiedStatus by sessionVerificationService.sessionVerifiedStatus.collectAsState()
```
Comment (bmarty) [inline features/verifysession/impl/src/main/kotlin/io/element/android/features/verifysession/impl/VerifySelfSessionPresenter.kt:78]: Do not use `needsSessionVerification` to avoid the initial `true` value.

**Review by ganfra — APPROVED** [review]
