### PR TITLE
Fix crash in work manager

### LINKED ISSUE #5765: Crash in WorkManager
### Steps to reproduce

Not sure how to repro but seen in several [rageshakes](https://github.com/element-hq/element-x-android-rageshakes/issues?q=is%3Aissue%20state%3Aopen%20%22Data%20cannot%20occupy%20more%20than%22):

>Thread: main, Exception: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
at coil3.util.BitmapsKt.toByteArrayInternalV1(SourceFile:96)
at androidx.work.Data$Builder.build(SourceFile:8)
at io.element.android.libraries.workmanager.impl.DefaultWorkManagerScheduler.submit(SourceFile:168)
at io.element.android.libraries.push.impl.notifications.DefaultNotificationResolverQueue$processQueue$1$1.invokeSuspend(SourceFile:244)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)

#### What did you expect?

No crash

#### What happened instead?
Crash

### Your phone model

?

### Operating system version

?

### Application version and app store

25.11.2 and below

### Homeserver

Any?

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by bmarty**
## Content

When lots of Pushes are received (for instance after a night of airplane mode), the WorkManager data that the application is building can be too large and this ends with a crash. And more annoyingly, all the pending notifications are lost.
The changes aim to catch such cases and split the requests in smaller set of data with all Pushes for the same rooms staying in the same chunk.

## Motivation and context

Less crash, notification reliability
Fixes #5765

## Tests

- enter airplane mode
- ensure that the app receive at least 65 Pushes (according to logs in rageshakes)
- observe that the notification are displayed
- when starting the application, no "App has crashed" popup is displayed.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 24
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] You've made a self review of your PR

### CODE REVIEW

File: libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/workmanager/SyncNotificationWorkManagerRequest.kt [hunk 1]
```diff
@@ -29,30 +29,29 @@ class SyncNotificationWorkManagerRequest(
...
-            OneTimeWorkRequestBuilder<FetchNotificationsWorker>()
-                .setInputData(data)
-                .apply {
-                    // Expedited workers aren't needed on Android 12 or lower:
-                    // They force displaying a foreground sync notification for no good reason, since they sync almost immediately anyway
-                    // See https://developer.android.com/develop/background-work/background-tasks/persistent/getting-started/define-work#backwards-compat
-                    if (buildVersionSdkIntProvider.isAtLeast(Build.VERSION_CODES.TIRAMISU)) {
-                        setExpedited(OutOfQuotaPolicy.RUN_AS_NON_EXPEDITED_WORK_REQUEST)
+        return workerDataConverter.serialize(notificationEventRequests).map {
+            it.map { data ->
```
Comment (jmartinesp) [inline libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/workmanager/SyncNotificationWorkManagerRequest.kt]: nit: maybe add some parameter names to disambiguate `it`s?

File: libraries/push/impl/src/test/kotlin/io/element/android/libraries/push/impl/workmanager/WorkerDataConverterTest.kt [hunk 2]
```diff
@@ -45,10 +47,83 @@ class WorkerDataConverterTest {
         )
     }
 
+    @Test
+    fun `serializing lots of data leads to several work data generated`() {
```
Comment (jmartinesp) [inline libraries/push/impl/src/test/kotlin/io/element/android/libraries/push/impl/workmanager/WorkerDataConverterTest.kt]: The titles could be more descriptive than `case 1/2/3` 😅 .

File: libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/workmanager/SyncNotificationWorkManagerRequest.kt (hunk 1 above)
Comment (bmarty) [reply libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/workmanager/SyncNotificationWorkManagerRequest.kt]: That is what I did (`data`), the remaining `it` here is of type `List<Data>` and I am not sure about what could be a good name to use. Any suggestion?

Comment (jmartinesp) [reply libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/workmanager/SyncNotificationWorkManagerRequest.kt]: `dataList` or `chunk`?
