### PR TITLE
Optional thumbnails

### LINKED ISSUE #2053: Make thumbnail optional
Now that's https://github.com/matrix-org/matrix-rust-sdk/pull/2940 is available the app is allow to send a media even if the thumbnail computation fails.

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [x] Technical
- [ ] Other :

## Content

Computing thumbnail may fail, but in this case it should not prevent the media from being sent. This PR handle this.

## Motivation and context

Close #2053 

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/ThumbnailFactory.kt [hunk 1]
```diff
@@ -61,26 +63,36 @@ class ThumbnailFactory @Inject constructor(
...
-                    Size(THUMB_MAX_WIDTH, THUMB_MAX_HEIGHT),
-                    cancellationSignal
-                )
-            } else {
-                @Suppress("DEPRECATION")
-                ThumbnailUtils.createImageThumbnail(
-                    file.path,
-                    MediaStore.Images.Thumbnails.MINI_KIND,
-                )
+            try {
```
Comment (bmarty) [inline libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/ThumbnailFactory.kt:68]: Global try catch for the tests...

**Review by ganfra — APPROVED** [review]
LGTM.
