### PR TITLE
Call: ensure that the microphone is working when the application is backgrounded.

### LINKED ISSUE #3679: Bluetooth mic muted during call if the app is not in foreground and the screen is on
### Steps to reproduce

When calling using a Bluetooth headset I must keep Element-X in foreground and keep the screen on. If I turn it off or background the app my mic goes silent.

### Outcome

The mic is muted as soon as the screen is off or the app is in background without picture in picture.

### Your phone model

_No response_

### Operating system version

Android 14

### Application version and app store

0.6.4

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Request audio focus only when the call is actually started and start the foreground service as soon as the call is started.
Second commit change the service permission. We do not really need the permission `MANAGE_OWN_CALLS` but are rather interested by `FOREGROUND_SERVICE_MICROPHONE`. 

## Motivation and context

Close #3679 

## Tests

- Start a call
- put the app in BG
- Switch the screen of.

the call should stay active, with a working microphone

## Tested devices

- [x] Physical running Android 14.
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/ElementCallActivity.kt [hunk 1]
```diff
@@ -115,6 +120,11 @@ class ElementCallActivity :
         }
     }
 
+    private fun setCallIsActive() {
+        requestAudioFocus()
+        CallForegroundService.start(this)
```
Comment (jmartinesp) [inline features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/ElementCallActivity.kt:125]: Don't we ever stop the foreground service?

File: features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/CallScreenPresenter.kt [hunk 2]
```diff
@@ -180,6 +180,7 @@ class CallScreenPresenter @AssistedInject constructor(
             urlState = urlState.value,
             webViewError = webViewError,
             userAgent = userAgent,
+            isCallActive = isJoinedCall,
```
Comment (jmartinesp) [inline features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/CallScreenPresenter.kt:183]: Have you checked this also works for URL-based calls? I'm not sure `isJoinedCall` is ever set to `true` for those.

File: features/call/impl/src/main/kotlin/io/element/android/features/call/impl/services/CallForegroundService.kt [hunk 3]
```diff
@@ -33,8 +35,12 @@ import timber.log.Timber
 class CallForegroundService : Service() {
     companion object {
         fun start(context: Context) {
-            val intent = Intent(context, CallForegroundService::class.java)
-            ContextCompat.startForegroundService(context, intent)
+            if (ContextCompat.checkSelfPermission(context, Manifest.permission.RECORD_AUDIO) == PackageManager.PERMISSION_GRANTED) {
```
Comment (jmartinesp) [inline features/call/impl/src/main/kotlin/io/element/android/features/call/impl/services/CallForegroundService.kt:38]: Really weird corner case, but what happens if the user didn't enable the microphone permission and joined the room anyway? Will the audio from the other side still be heard, even when the device is locked? I assume it would work for the app just being in background since the PiP window is alive.

**Review by jmartinesp — COMMENTED** [review]
There are a few things I'd like to double check.

File: features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/ElementCallActivity.kt (hunk 1 above)
Comment (bmarty) [reply features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/ElementCallActivity.kt:125]: Yes, I kept the existing code in `onDestroy()`

Comment (jmartinesp) [reply features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/ElementCallActivity.kt:125]: Oh, I didn't see it in the diff, so I assumed it wasn't there 🤦 . Thanks!

File: features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/CallScreenPresenter.kt (hunk 2 above)
Comment (bmarty) [reply features/call/impl/src/main/kotlin/io/element/android/features/call/impl/ui/CallScreenPresenter.kt:183]: https://github.com/element-hq/element-x-android/pull/3685/commits/cf80b3b804fe99363d5a988f2295f92ddb04f56a

**Review by jmartinesp — APPROVED** [review]
Thanks for the changes, the feature now seems a lot more stable and useful!

**Comment by jmartinesp** [comment]
cc @toger5 since he was especially interested in this. He might also be a good early tester 😛 .

**Comment by davidegirardi** [comment]
I tested the latest nightly. It failed on the very first call but then worked with no issues, even if I revoked the picture in picture permissions.
