### PR TITLE
Strip formatting from media captions in room summary

### LINKED ISSUE #6542: Markdown captions are shown unformatted in the room list
### Steps to reproduce

1. Have a room where the latest message has caption with Markdown at start

#### What did you expect?

Either (depends on what the Product team decides):
* Show the message formatted (but the message might be done on purpose e.g. in bold at start to catch attention for the specific room)
* Remove formatting from message in summary

#### What happened instead?

The message is shown literally without rendering formatting

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by bxdxnn**
## Motivation and context

Fixes #6542

Media captions used plain `body` instead of removing formatting from `formatted_body` like in normal messages.

## Tests

- Test that media captions are displayed without markups in the room summary

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- This PR was made with the help of AI:
    - [x] Yes. In this case, please request a review by Copilot.
    - [ ] No.
- [ ] Changes have been tested on an Android device or Android emulator with API 24
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly defines what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [x] You've made a self review of your PR

### CODE REVIEW

File: libraries/eventformatter/impl/src/main/kotlin/io/element/android/libraries/eventformatter/impl/DefaultRoomLatestEventFormatter.kt [hunk 1]
```diff
@@ -139,27 +139,30 @@ class DefaultRoomLatestEventFormatter(
...
             }
             is VoiceMessageType -> {
                 // In this case, do not use bestDescription, because the filename is useless, only use the caption if available.
-                messageType.caption?.prefixWith(sp.getString(CommonStrings.common_voice_message))
-                    ?: sp.getString(CommonStrings.common_voice_message)
+                messageType.caption?.let { caption ->
+                    // Use toPlainText to convert formatted caption to plain text
+                    val plainCaption = messageType.formattedCaption?.toPlainText(permalinkParser) ?: caption
+                    plainCaption.prefixWith(sp.getString(CommonStrings.common_voice_message))
+                } ?: sp.getString(CommonStrings.common_voice_message)
```
Comment (bmarty) [inline libraries/eventformatter/impl/src/main/kotlin/io/element/android/libraries/eventformatter/impl/DefaultRoomLatestEventFormatter.kt]: This code is strange. Why checking `caption` to then use `formattedCaption`?

Maybe rewrite a bit the new extension `fun MessageTypeWithAttachment.toPlainText()` like this:

```kotlin
fun MessageTypeWithAttachment.toPlainText(
    permalinkParser: PermalinkParser,
    default: String = filename,
): String {
    val plainTextFromFormatted = formattedCaption?.toPlainText(permalinkParser)
    return plainTextFromFormatted ?: caption ?: default
}
```

And in this particular case provide `""` for the parameter `default`. This code will become:
```kotlin
messageType
    .toPlainText(permalinkParser, "")
    .takeIf { it.isNotEmpty() }
    ?.prefixWith(sp.getString(CommonStrings.common_voice_message))
    ?: sp.getString(CommonStrings.common_voice_message)
```

Also the comment above could be updated / deleted.

I let you ensure that my proposal make sense, I did not test it.

File: libraries/eventformatter/impl/src/main/kotlin/io/element/android/libraries/eventformatter/impl/DefaultPinnedMessagesBannerFormatter.kt [hunk 2]
```diff
@@ -77,27 +77,29 @@ class DefaultPinnedMessagesBannerFormatter(
...
+                messageType.toPlainText(permalinkParser).prefixWith(CommonStrings.common_audio)
             }
             is VoiceMessageType -> {
                 // In this case, do not use bestDescription, because the filename is useless, only use the caption if available.
-                messageType.caption?.prefixWith(sp.getString(CommonStrings.common_voice_message))
-                    ?: sp.getString(CommonStrings.common_voice_message)
+                messageType.caption?.let { caption ->
+                    val plainCaption = messageType.formattedCaption?.toPlainText(permalinkParser) ?: caption
+                    plainCaption.prefixWith(sp.getString(CommonStrings.common_voice_message))
+                } ?: sp.getString(CommonStrings.common_voice_message)
```
Comment (bmarty) [inline libraries/eventformatter/impl/src/main/kotlin/io/element/android/libraries/eventformatter/impl/DefaultPinnedMessagesBannerFormatter.kt]: See my other comment.

**Review by bmarty — COMMENTED** [review]
Make sense, thanks. Please see my comments.

**Review by bmarty — APPROVED** [review]
Thanks for the update!
