### PR TITLE
[Link new device] Add missing error case "already signed in"

### LINKED ISSUE #6678: Missing "Your other device is already sign in" screen for Link new device flow
### Steps to reproduce

You need two device to reproduce this:
 
1. Launch EX Android
2. Sign in manually to a homeserver that supports the MSC4108 sign in (e.g. `element.io`) and verify device.
3. Go to "Link new device" on the settings menu.
4. Press "Desktop computer"
5. Press "Ready to scan"
6. On another logged in EX device: Go to "Link new device" on settings menu
7. Press "Mobile device"
8. A QR code will show
9. Use the Android to scan the QR from the other EX device

#### What did you expect?

To see the screen from the [Figma design](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=2186-70012&t=s7CiywDOj5rokR8y-4):

Image

#### What happened instead?

I saw this screen instead:

Image

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Add missing case when the user is scanning a QR code from an already logged in device

## Motivation and context

Closes #6678 

## Screenshots / GIFs

https://github.com/user-attachments/assets/f8640bc1-3cd8-4e07-b710-c365cb4dbdd7

## Tests

You need two devices to reproduce this:

- Launch EX Android
- Sign in manually to a homeserver that supports the MSC4108 sign in (e.g. element.io) and verify device.
- Go to "Link new device" on the settings menu.
- Press "Desktop computer"
- Press "Ready to scan"
- On another logged in EX device: Go to "Link new device" on settings menu
- Press "Mobile device"
- A QR code will show
- Use the Android to scan the QR from the other EX device

## Tested devices

- [x] Physical for the device which scan
- [x] Emulator for the other one
- OS version(s):

## Checklist

- This PR was made with the help of AI:
    - [ ] Yes. In this case, please request a review by Copilot.
    - [ ] No.
- [ ] Changes have been tested on an Android device or Android emulator with API 24
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly defines what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] You've made a self review of your PR

### CODE REVIEW

File: libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/pages/FlowStepPage.kt [hunk 1]
```diff
@@ -71,7 +71,7 @@ fun FlowStepPage(
         },
         header = {
             IconTitleSubtitleMolecule(
-                modifier = Modifier.padding(bottom = 16.dp),
+                modifier = Modifier.padding(bottom = 16.dp, start = 8.dp, end = 8.dp),
```
Comment (bmarty) [inline libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/pages/FlowStepPage.kt:74]: Design wants a total of 24dp for the <del>vertical</del> horizontal padding, see here for instance: https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=2186-70012&m=dev

and I guess it's fine to apply the padding to all our FlowStepPage usage.

Comment (jmartinesp) [reply libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/pages/FlowStepPage.kt:74]: That's only adding *horizontal* padding though?

Comment (bmarty) [reply libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/pages/FlowStepPage.kt:74]: sure, fixed

Comment (jmartinesp) [reply libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/pages/FlowStepPage.kt:74]: Ok, thanks, I was confused thinking I had missed some other part of the code where the vertical padding was added 😅 .

**Review by jmartinesp — APPROVED** [review]
Thanks!
