### PR TITLE
Let Dms use other member color.

### LINKED ISSUE #1538: DM and user color are different
### Steps to reproduce

1. i have a DM with a user that has no avatar set
2. the DM's name and avatar is usually interpolated based on that other user's name and avatar
3. since none is set, the interpolation should use the placeholder avatar (=color)

#### What did you expect?
on web (and all other DMs I can find), the colors of DMs match those of the "other" participant. That includes "DMs" with more than 2 participants, that joined after the "primary" other participant.
#### What happened instead?
the DM avatar placeholder is purple, but the user's placeholder and displayname color is green

### Your phone model

fairphone

### Operating system version

13

### Application version

selfbuilt last week

### Homeserver

matrix.org

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Ensure that a DM will use the same color that the other user color.

Preparatory work for a wider rendering of heroes. Note: the rendering of multiple heroes is currently disabled by ac6e56fead9bccadd74712825c63a62af615262c.

## Motivation and context

Closes #1538

## Screenshots / GIFs

For the user:

image

Here is how it is rendered in the room list: 

|Before|After|
|-|-|
|image|Screenshot 2024-06-20 at 14 37 38|

## Tests

- Observer the default color of DM room.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/roomdetails/impl/src/main/kotlin/io/element/android/features/roomdetails/impl/RoomDetailsView.kt [hunk 1]
```diff
@@ -332,10 +335,17 @@ private fun RoomHeaderSection(
...
+            heroes = heroes.map { user ->
+                AvatarData(
+                    id = user.userId.value,
+                    name = user.displayName,
+                    url = user.avatarUrl,
+                    size = AvatarSize.RoomHeader
+                )
+            },
             modifier = Modifier
-                .size(70.dp)
```
Comment (bmarty) [inline features/roomdetails/impl/src/main/kotlin/io/element/android/features/roomdetails/impl/RoomDetailsView.kt:338]: This removal is actually fixing a rendering issue, see the recorded screenshot. The Avatar was not rendered correctly.

**Review by ganfra — APPROVED** [review]
