### PR TITLE
Replace the 'answer' PendingIntent in ringing call notifications

### LINKED ISSUE #3085: Broken pending intent when accepting a incoming call via the OS notification banner.
### Steps to reproduce

1. Where are you starting? What can you see?

Anywhere in my phone (unlocked)

I receive A ring notification.
2. What do you click?
and click accept (video).
3. More steps…
I wait and the person who called me stays in their room by themselves and I started a call with another different user. (also sending another ring event)

#### What did you expect?
Join the call shown in the notification where I clicked on the accept (video) button
#### What happened instead?
Joined a different call.

### Your phone model

S21

### Operating system version

_No response_

### Application version and app store

0.4.15

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Added the `CANCEL_CURRENT` flag to the pending intent so it's replaced.

## Motivation and context

Fixes #3085.

## Tests

- Receive a ringing call from another user. Ignore or decline it.
- Receive a new one from a different user, answer it.

The call you join should be the 2nd one, not the first one.

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 14

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

### CODE REVIEW

File: changelog.d/3085.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Make sure we replace the 'asnwer call' pending intent on ringing call notifications.
```
Comment (bmarty) [inline changelog.d/3085.bugfix:1]:
```suggestion
Make sure we replace the 'answer call' pending intent on ringing call notifications.
```

Also this description is quite technical. For the user, what will be the impact of this change?

**Review by bmarty — APPROVED** [review]
OK, just a question about the impact for the user.

**Comment by toger5** [comment]
Super nice to have this fixes so quickly.
