### PR TITLE
Hide call member events

### LINKED ISSUE #2625: The timeline is rendering event `org.matrix.msc3401.call.member`
### Steps to reproduce

1. Start a call in a room
2. End the call
3. Observe the timeline

image

The event  of type `org.matrix.msc3401.call.member` should be filtered out. EXI seems to filter them out.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- First commit is preparatory work around permalink. It will be need to properly handle permalink computation, when it will be done by the SDK. Need to do this rework now to avoid a circular dependency (see 2nd commit)
- Second commit: move filtered Event configuration to the appconfig module
- Third commit: fixes #2625 

## Motivation and context

Fixes #2625 and prepare work around permalink

## Screenshots / GIFs

No impact.

## Tests

- In a room with a call, observe the the CallMember Events are not rendered anymore.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/MessagesNode.kt [hunk 1]
```diff
@@ -96,6 +103,25 @@ class MessagesNode @AssistedInject constructor(
...
+    private fun onLinkClicked(
+        context: Context,
+        url: String,
+    ) {
+        when (val permalink = permalinkParser.parse(Uri.parse(url))) {
+            is PermalinkData.UserLink -> {
+                onUserDataClicked(UserId(permalink.userId))
+            }
+            is PermalinkData.RoomLink -> {
+                // TODO: Implement room link handling
```
Comment (ElementBot) [inline features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/MessagesNode.kt:116]: - :warning: Forbidden TODO todo marker in comment, please do the changes.

File: libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/permalink/DefaultMatrixToConverter.kt [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+            SUPPORTED_PATHS.any { it in uriString } -> {
+                val path = SUPPORTED_PATHS.first { it in uriString }
+                Uri.parse(baseUrl + uriString.substringAfter(path))
+            }
+            // URL is not supported
+            else -> null
+        }
+    }
+
+    private val SUPPORTED_PATHS = listOf(
```
Comment (ElementBot) [inline libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/permalink/DefaultMatrixToConverter.kt:56]: - :warning: Private variable names should match the pattern: (_)?[a-z][A-Za-z0-9]*

File: libraries/matrix/test/src/main/kotlin/io/element/android/libraries/matrix/test/permalink/FakePermalinkParser.kt [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+ */
+
+package io.element.android.libraries.matrix.test.permalink
+
+import android.net.Uri
+import io.element.android.libraries.matrix.api.permalink.PermalinkData
+import io.element.android.libraries.matrix.api.permalink.PermalinkParser
+
+class FakePermalinkParser(
+    private var result: () -> PermalinkData = { throw Exception("Not implemented") }
```
Comment (ElementBot) [inline libraries/matrix/test/src/main/kotlin/io/element/android/libraries/matrix/test/permalink/FakePermalinkParser.kt:24]: - :warning: Exception is a too generic Exception. Prefer throwing specific exceptions that indicate a specific error case.

File: libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/permalink/MatrixToConverter.kt [hunk 4]
```diff
@@ -17,40 +17,18 @@
...
 
 /**
  * Mapping of an input URI to a matrix.to compliant URI.
  */
-object MatrixToConverter {
+interface MatrixToConverter {
     /**
      * Try to convert a URL from an element web instance or from a client permalink to a matrix.to url.
-     * To be successfully converted, URL path should contain one of the [SUPPORTED_PATHS].
+     * To be successfully converted, URL path should contain one of the [DefaultMatrixToConverter.SUPPORTED_PATHS].
```
Comment (jmartinesp) [inline libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/permalink/MatrixToConverter.kt:27]: Shouldn't we move the constant here, or maybe not mention the concrete implementation?

**Review by jmartinesp — APPROVED** [review]

File: libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/permalink/MatrixToConverter.kt (hunk 4 above)
Comment (bmarty) [reply libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/permalink/MatrixToConverter.kt]: I have removed the comment.
