### PR TITLE
Ensure that the manual dark theme is rendering correctly regarding -night resource and keyboard

### LINKED ISSUE #3168: Assets in `-nightly` folder are not used when theme is forced to "Dark"
### Steps to reproduce

1. The device main theme is set to `Light`
2. In the advanced settings of the application, set the theme to `Dark`
3. Share your location to any room
4. Clear cache
5. Kill the app
6. Enter airplane mode
7. Start the app and navigate to the room the location was shared

#### What did you expect?

The dark version of the blurred map is used

#### What happened instead?

The light version of the blurred map is used

image

There is a similar issue with all the assets with alternative stored in `-night` resource folder, and the Sunset page is not working as expected in the similar condition (Light system, Dark application)

We can fix by using `AppCompatDelegate.setDefaultNightMode`, but I think it will be easier to not use `-night` resource folder at all and create alternative resource with `-dark` suffix.

### Your phone model

Any

### Operating system version

Any

### Application version and app store

Latest

### Homeserver

Any

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Ensure that the system is aware about "forced" dark theme.
Using `AppCompatDelegate.setDefaultNightMode` is actually working like a charm, I have not found any regression.

## Motivation and context

Full dark theme when system setting is set to light and application setting is set to dark.

Closes #3168 

## Screenshots / GIFs

|Before|After|
|-|-|
|Screenshot 2024-07-18 at 14 34 45|Screenshot 2024-07-18 at 14 34 51|

## Tests

- Set system theme to light
- Set application theme to dark
- Before: keyboard was light and some screens were broken (see #3168)
- Clear cache from the application: observe that before the screen was quite broken and is OK now.

Try to change system theme and application theme and observe that the application is always rendering the expected theme.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/theme/ElementThemeApp.kt [hunk 1]
```diff
@@ -39,6 +44,15 @@ fun ElementThemeApp(
...
         .collectAsState(initial = Theme.System)
+    LaunchedEffect(theme) {
+        AppCompatDelegate.setDefaultNightMode(
+            when (theme) {
+                Theme.System -> AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM
+                Theme.Light -> AppCompatDelegate.MODE_NIGHT_NO
+                Theme.Dark -> AppCompatDelegate.MODE_NIGHT_YES
+            }
+        )
+    }
```
Comment (bmarty) [inline libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/theme/ElementThemeApp.kt:55]: Note that it could be done elsewhere, for instance in `RootPresenter`, but when the value is the same, `setDefaultNightMode` has no effect, so I guess it's fine to do it here.

**Review by ganfra — APPROVED** [review]
LGTM!
