### PR TITLE
Fix broken Element Call in 25.05.0

### LINKED ISSUE #4689: Update 25.5.0 broke element-call
### Steps to reproduce

1. Where are you starting? What can you see?
Start an element call between androids

#### What did you expect?
Call to connect with the implemented avatar display

#### What happened instead?

Image

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Ensure that the Rust room is not closed while the driver needs it.
I tried to make a wider rework by just using a Room (from Rust), but it does not work since we need an active timeline.

## Motivation and context

Fix regression introduced in #4678 and so closes #4689

## Tests

- Start a call
- The call starts

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 24
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/call/impl/src/main/kotlin/io/element/android/features/call/impl/utils/DefaultCallWidgetProvider.kt [hunk 1]
```diff
@@ -48,7 +48,6 @@ class DefaultCallWidgetProvider @Inject constructor(
         ).getOrThrow()
 
         val driver = room.getWidgetDriver(widgetSettings).getOrThrow()
-        room.destroy()
```
Comment (bmarty) [inline features/call/impl/src/main/kotlin/io/element/android/features/call/impl/utils/DefaultCallWidgetProvider.kt:51]: We cannot destroy the room here since it will close the FFI Room and the WidgetDriver needs it to work properly.

Comment (jmartinesp) [reply features/call/impl/src/main/kotlin/io/element/android/features/call/impl/utils/DefaultCallWidgetProvider.kt:51]: Thanks, and sorry for the regression 😞 .

**Review by jmartinesp — APPROVED** [review]
