### PR TITLE
Ensure the form data are not lost when opening the log viewer.

### LINKED ISSUE #5579: Bug: Text and Cursor Position Lost After Navigating Away from "Report a problem" View
### Steps to reproduce

1. Navigate to the "Report a problem" view.
2. Type some text into the "Describe the problem..." textbox.
3. Navigate away from the view by clicking the "View logs" button.
4. Navigate back to the "Report a problem" view.

#### What did you expect?

I would expect any text I have entered into the textbox to remain, as well as the position of the cursor.

#### What happened instead?

All text entered into the textbox is removed.

### Your phone model

Fairphone 5

### Operating system version

Android 15

### Application version and app store

Element X 25.10.1 installed via Obtainium

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Ensure the form data are not lost when opening the log viewer.

## Motivation and context

Closes #5579 

## Tests

- Open the bug report screen
- Type a few word
- update some switch
- open the log viewer
- go back
- the form state is restored

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 24
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/rageshake/impl/src/main/kotlin/io/element/android/features/rageshake/impl/bugreport/BugReportPresenter.kt [hunk 1]
```diff
@@ -32,7 +32,7 @@ class BugReportPresenter(
     private val bugReporter: BugReporter,
     private val crashDataStore: CrashDataStore,
     private val screenshotHolder: ScreenshotHolder,
-    @AppCoroutineScope
+    @param:AppCoroutineScope
```
Comment (ganfra) [inline features/rageshake/impl/src/main/kotlin/io/element/android/features/rageshake/impl/bugreport/BugReportPresenter.kt]: Why this `param`?

Comment (bmarty) [reply features/rageshake/impl/src/main/kotlin/io/element/android/features/rageshake/impl/bugreport/BugReportPresenter.kt]: This is fixing a warning from the IDE and I believe it is correct, but it looks like detekt is not ready for this.
Removing for now.

**Review by ganfra — APPROVED** [review]
