### PR TITLE
Redact message on displayed notification

### LINKED ISSUE #3310: Redacted messages continue to show in notification previews
### Steps to reproduce

1. Send an image from another client
2. Receive the notification on Element X which shows the image
3. Redact the image on the other client
4. Notice how the notification on Element X still shows the image

Message with image redacted on Element Web:

Screenshot 2024-08-20 at 09 15 32

Element X still showing the image in the notification:

01fab203-0550-4228-a8ed-388fa3bc37d37530435372318880093

This might seem fairly benign, however, last night there was a CSAM assault on one of the public Foundation rooms. Even hours after the attacker had been banned and their messages redacted, Element X on my phone still continued to present me the pornographic pictures in the unread notification.

#### What did you expect?

Redacted images should not show in notifications.

#### What happened instead?

They continued to show post redaction.

### Your phone model

Google Pixel 6

### Operating system version

14

### Application version and app store

0.5.0

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Ensure that any message currently displayed in a notification is removed when the Event is redacted.

Note: request SDK change in https://github.com/matrix-org/matrix-rust-sdk/pull/3868.

## Motivation and context

Closes #3310 

## Screenshots / GIFs

NotificationRedaction

## Tests

- Alice send a message to Bob and Bob observes the notification
- Alice redacts the message
- Bob now see the the message is replaced by "Message removed" in the notification. 

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/notifications/factories/NotificationCreator.kt [hunk 1]
```diff
@@ -418,6 +418,7 @@ class DefaultNotificationCreator @Inject constructor(
                         event.imageUri?.let {
                             message.setData("image/", it)
                         }
+                        message.extras.putString(MESSAGE_EVENT_ID, event.eventId.value)
```
Comment (bmarty) [inline libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/notifications/factories/NotificationCreator.kt:421]: Put the `eventId` into the bundle so that we may be able to find the message to redact it.

File: libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/notification/TimelineEventToNotificationContentMapper.kt [hunk 2]
```diff
@@ -94,7 +95,10 @@ private fun MessageLikeEventContent.toContent(senderId: UserId): NotificationCon
             is MessageLikeEventContent.RoomMessage -> {
                 NotificationContent.MessageLike.RoomMessage(senderId, EventMessageMapper().mapMessageType(messageType))
             }
-            is MessageLikeEventContent.RoomRedaction -> NotificationContent.MessageLike.RoomRedaction(redactedEventId = redactedEventId, reason = reason)
+            is MessageLikeEventContent.RoomRedaction -> NotificationContent.MessageLike.RoomRedaction(
+                redactedEventId = redactedEventId?.let(::EventId),
```
Comment (ganfra) [inline libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/notification/TimelineEventToNotificationContentMapper.kt:99]: Maybe `NotificationContent.MessageLike.RoomRedaction.redactedEventId` should be an `EventId` instead?

Comment (bmarty) [reply libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/notification/TimelineEventToNotificationContentMapper.kt:99]: Yes, it's the case. If you mean `MessageLikeEventContent.RoomRedaction.redactedEventId` it's a type from the SDK, so it's a `String`.
