### PR TITLE
Fix password flow when using a login link

### LINKED ISSUE #5004: Mobile provisioning deeplink wording change
### Steps to reproduce

This bug is in reference to the new deeplink feature found https://ems-docs.element.io/link/893#bkmrk-how-to-create-the-de

When you hit the deeplink url it will take you to the "sign in to https://your-server/" page, but then when you click this button and go to the next page it says "You're about to sign into [matrix.org](http://matrix.org/)" when in reality you are signing into your-server. So I think we just need to change the wording on the 2nd screen.

Reproduce by:
1. Set up a deeplink https://mobile.element.io/element-pro/?account_provider=https://<server-domain>
2. Hit the link and it will take you to the below screenshot 

Image

3. Click the button and it will take you to the below screenshot 

Image

4. Proceed to login and it will log you into the server defined in the deeplink url (not matrix.org)

#### What did you expect?

Expect to see "you're about to sign in to <your-server>" 

#### What happened instead?

I saw "you're about to sign in to matrix.org" 

### Your phone model

Pixel 8

### Operating system version

Android 16

### Application version and app store

Element Pro 25.06.0

### Homeserver

_No response_

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Content

When using a login link that contains a homeserver with login password login type, the account provider displayed in the login password form was not correct.
This PR fixes this and also improves the codebase.

Will be rebased on develop once the other PR has been merged.

## Motivation and context

Closes #5004

## Screenshots / GIFs

By hacking the code to force element.io homeserver to have a login password configuration, open this link with the app: `https://mobile.element.io/element/?account_provider=element.io`

https://github.com/user-attachments/assets/488852e8-ce36-427f-8266-b179ed3dedc2

## Tests

- Build a permalink of type login, with a server that request a login password. Example: `https://mobile.element.io/element/?account_provider=element.io`
- Open the link with the app
- Observe that the button to login on `element.io` is displayed
- Click it
- Observe that the form now contain `element.io` in the subtitle and not `matrix.org` 

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 24
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/login/impl/src/main/kotlin/io/element/android/features/login/impl/screens/onboarding/OnBoardingPresenter.kt [hunk 1]
```diff
@@ -97,12 +100,15 @@ class OnBoardingPresenter(
...
             when (event) {
-                is OnBoardingEvents.OnSignIn -> loginHelper.submit(
-                    coroutineScope = localCoroutineScope,
-                    isAccountCreation = false,
-                    homeserverUrl = event.defaultAccountProvider,
-                    loginHint = params.loginHint?.takeIf { forcedAccountProvider == null },
-                )
+                is OnBoardingEvents.OnSignIn -> localCoroutineScope.launch {
+                    // Ensure that the current account provider is set
+                    accountProviderDataSource.setUrl(event.defaultAccountProvider)
```
Comment (bmarty) [inline features/login/impl/src/main/kotlin/io/element/android/features/login/impl/screens/onboarding/OnBoardingPresenter.kt:105]: Here is the fix
