### PR TITLE
Fix read receipt behavior when the timeline is opened.

### LINKED ISSUE #4662: "Seen" status only populate when target user exit and re-enter room not if they are already in the room
### Steps to reproduce

1. Where are you starting? What can you see?
send a message and wait for the message to be seen.

if the target user is already in the room (i.e. app open and in the room and can see the messages coming through) the seen status is not displayed on the origin device.

But is the target user go out of the room and re-enter the room the seen status in the origin device populate properly.

#### What did you expect?
the seen status to be updated in the origin device if the target device is on and the user is already in the room

#### What happened instead?
seen status not updating even through the target user saw the message

### Your phone model

Samsung Galaxy

### Operating system version

_No response_

### Application version and app store

25.04.03

### Homeserver

1.128.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Ensure that ReadReceipt is sent when new messages are coming in and user is on the timeline.

## Motivation and context

Closes #4662 

## Tests

- Alice opens a room R she shares with Bob
- Bob open the same room
- Bob sees that Alice RR is at the bottom of the timeline
- Bob sends a new message
- Alice views the message from Bob and does not do anything else particular
- Bob sees Alice's RR moving down as expected. This PR fixes this, previously Alice RR did not move.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 24
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/TimelinePresenter.kt [hunk 1]
```diff
@@ -278,7 +279,10 @@ class TimelinePresenter @AssistedInject constructor(
         if (newEventState.value == NewEventState.FromMe) {
             return@withContext
         }
-        val newMostRecentItem = timelineItems.firstOrNull()
+        val newMostRecentItem = timelineItems.firstOrNull {
+            // Ignore typing item
+            (it as? TimelineItem.Virtual)?.model !is TimelineItemTypingNotificationModel
+        }
```
Comment (jmartinesp) [inline features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/TimelinePresenter.kt:285]: Oh, good catch 👌 .

**Review by jmartinesp — APPROVED** [review]

File: features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/TimelinePresenter.kt (hunk 1 above)
Comment (bmarty) [reply features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/TimelinePresenter.kt:285]: Yes, I could also have dropped the first item, but I guess it's more accurate like this.

**Comment by bmarty** [comment]
@jmartinesp I have updated the fix to fix regression on tests.

I have tested again and the fix is still working (there is no tests covering the use case). Can you have a second look please? Thanks!

**Review by jmartinesp — APPROVED** [review]
