### PR TITLE
Do not delete the original file if it's not a temporary file when sending it to a room.

### LINKED ISSUE #3800: Sharing to Element X from certain apps deletes original files
### Steps to reproduce

When sharing an item (image, video, text file, etc) to element X from a number of different apps, the original file is silently deleted. 
Apps which result in deletion: F-stop, MiXplorer 
Apps which don't: Google Files, Google Photos, Directly attaching from within Element X
All apps on the latest play store versions, and I don't encounter this issue sharing from any of the mentioned apps to the legacy Element client or other messaging clients.

#### What did you expect?
File to be shared while maintaining original
#### What happened instead?
Original file is deleted after sharing

### Your phone model

Pixel 8 Pro

### Operating system version

Android 14

### Application version and app store

Element X Version 0.7.2

### Homeserver

Local Synapse server version 1.117.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by bmarty**
## Content

When sending file using Element X the original file may be deleted by the application. This is an error of course and this PR fixes it.

This PR also ensure that temporary files that are created when taking a photo or a video are correctly deleted if the process is cancelled. Else such file were living in the application `cache` folder until this one get deleted.

## Motivation and context

Fixes #3800

## Screenshots / GIFs

MediaDeletion

## Tests

- You may use apps from #3800 to test that the PR fixes the issue CC @vidyava
- Send a file from the camera and observe that even if the operation is cancelled, there is no remaining file in the cache folder of the app.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: tests/testutils/src/main/kotlin/io/element/android/tests/testutils/fake/FakeTemporaryUriDeleter.kt [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ */
+
+package io.element.android.tests.testutils.fake
+
+import android.net.Uri
+import io.element.android.libraries.androidutils.file.TemporaryUriDeleter
+import io.element.android.tests.testutils.lambda.lambdaError
+
+class FakeTemporaryUriDeleter(
+    val deleteCallback: (uri: Uri?) -> Unit = { lambdaError() }
```
Comment (ganfra) [inline tests/testutils/src/main/kotlin/io/element/android/tests/testutils/fake/FakeTemporaryUriDeleter.kt:15]: name it `deleteLambda` like we do elsewhere?

File: features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewPresenter.kt [hunk 2]
```diff
@@ -57,6 +60,20 @@ class AttachmentsPreviewPresenter @AssistedInject constructor(
 
         val ongoingSendAttachmentJob = remember { mutableStateOf<Job?>(null) }
 
+        DisposableEffect(Unit) {
```
Comment (ganfra) [inline features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewPresenter.kt:63]: What if it's disposed for some reason (new screen on the backstack, config changes not handled)?

Comment (bmarty) [reply features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewPresenter.kt:63]: Yes good point, so I guess I have to handle the cancellation with an event.

Comment (bmarty) [reply features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewPresenter.kt]: 62aab87c0924736cb29c3845ac94b1f8df64dcfd

File: tests/testutils/src/main/kotlin/io/element/android/tests/testutils/fake/FakeTemporaryUriDeleter.kt (hunk 1 above)
Comment (bmarty) [reply tests/testutils/src/main/kotlin/io/element/android/tests/testutils/fake/FakeTemporaryUriDeleter.kt]: b13605de7aa9a24f18bdb66bfbccb93417ad2794

**Comment by bmarty** [comment]
@ganfra thanks for the review, I have taken your remarks in to account. Let me know if it's fine for you!

File: features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewView.kt [hunk 3]
```diff
@@ -50,22 +48,22 @@ import me.saket.telephoto.zoomable.rememberZoomableState
...
     fun postClearSendState() {
         state.eventSink(AttachmentsPreviewEvents.ClearSendState)
     }
 
-    if (state.sendActionState is SendActionState.Done) {
-        val latestOnDismiss by rememberUpdatedState(onDismiss)
-        LaunchedEffect(state.sendActionState) {
-            latestOnDismiss()
-        }
+    BackHandler(enabled = state.sendActionState !is SendActionState.Sending) {
```
Comment (ganfra) [inline features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewView.kt:65]: Do we really need this check?

**Review by ganfra — COMMENTED** [review]
I've just realised this might be be incompatible with the new async media upload?

File: features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewView.kt (hunk 3 above)
Comment (bmarty) [reply features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewView.kt:65]: The cancellation during the sending state is emitting a `ClearSendState` event, so I did not want to change this behavior.

**Comment by ganfra** [comment]
> I've just realised this might be be incompatible with the new async media upload?

Lets rebase on develop with the latest changes and see how it reacts?

**Comment by vidyava** [comment]
I can confirm that the issue is fixed on my physical device with the debug build posted earlier. I'll give it another try with the rebased build when one is available. Thanks for the quick turnaround on this!

**Comment by bmarty** [comment]
It seems to work as expected 🎉

**Review by ganfra — APPROVED** [review]
